apiVersion: v1
kind: ReplicationController
metadata:
  name: sb-instanceid-kafka
spec:
  replicas: 3
  selector:
    sb-instanceid-kafka: kafka
  template:
    metadata:
      labels:
        sb-instanceid-kafka: kafka
        service-broker: sb-instanceid-kafka
    spec:
      containers:
      - name: kafka
        image: 172.30.188.59:5000/service-broker/kubernetes-kafka
        ports:
        - containerPort: 9092
        env:
          - name: KAFKA_RESERVED_BROKER_MAX_ID
            value: "999999999"
          - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
            value: "false"
          - name: KAFKA_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_PORT
            value: "9092"
          - name: KAFKA_ADVERTISED_HOST_NAME
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: BROKER_ID_PROTOTYPE
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: sb-instanceid-zk:2181
          - name: KAFKA_CREATE_TOPICS
            value: topic-test1:6:3